<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Login</title>
        <link href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700|Merriweather:400,700,900" rel="stylesheet">
            <style type="text/css">
                .altrowClass { background-color: gray; background-image: none }
            </style>
            <link href="/css/design.css" rel="stylesheet">
                </head>
                <body class="login">
                    <header id="master-header" class="clearfix" role="banner">

                        <hgroup>
                            <h1 id="site-title">Tempo</h1>

                        </hgroup>

                    </header>
                    <div id="main" class="row clearfix login">
<header class="entry-header">
                                    <h1 class="entry-title">
                                        Login
                                    </h1>

                                </header>
                        <form name="loginform" id="loginform" action="/profile" method="post">

                            <p class="login-username">
                                <label for="thim_login">Username</label>
                                <input type="text" name="username" id="username" class="input" value="" size="20" />
                            </p>
                            <p class="login-password">
                                <label for="thim_pass">Password</label>
                                <input type="password" name="password" id="password" class="input" value="" size="20" />
                            </p>

                            <p class="login-submit">
                                <input type="submit" name="wp-submit" id="wp-submit" class="button-primary" value="Login" />
                                <input type="hidden" name="redirect_to" value="http://tempo/profile" /></p>

                        </form>	
                    </div>

                </body>
                <script src="../app/Views/javascript/script.js"></script>
                </html>
